# Generated by Django 2.0.5 on 2018-07-29 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='adv_slug_name',
        ),
    ]
