# Generated by Django 2.0.3 on 2018-07-31 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('advertisement', '0002_advsummary_slug_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('influencer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencersummary',
            name='user',
        ),
        migrations.AddField(
            model_name='influencersummary',
            name='registered_Adv',
            field=models.ManyToManyField(to='advertisement.AdvSummary'),
        ),
        migrations.AddField(
            model_name='influencersummary',
            name='username',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                       to=settings.AUTH_USER_MODEL),
        ),
    ]
