# Generated by Django 2.0.3 on 2018-06-11 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvSummary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guid', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('adv_slug_name', models.SlugField(allow_unicode=True, null=True, unique=True)),
                ('brand_slug_name', models.SlugField(allow_unicode=True, null=True, unique=True)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=38)),
                ('max_fee_per_like', models.IntegerField()),
                ('expire_date', models.DateField()),
                ('adv_image',
                 models.ImageField(blank=True, null=True, upload_to='adv_image/', verbose_name='Advertisement Image')),
                ('adv_desc', models.CharField(max_length=255, null=True, verbose_name='Advertisement Description')),
                ('adv_min_follower', models.IntegerField(null=True, verbose_name='Advertisement Minimum Follower')),
                ('adv_max_follower', models.IntegerField(null=True, verbose_name='Advertisement Maximum Follower')),
                ('is_approved', models.BooleanField(default=0)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-publish_date'],
                'verbose_name': 'advertisement_summary',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('insert_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('username', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                  to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('insert_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='advsummary',
            name='categories',
            field=models.ManyToManyField(to='advertisement.Category'),
        ),
        migrations.AddField(
            model_name='advsummary',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
