# Generated by Django 2.0.5 on 2018-07-14 13:03

import advertisement.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guid', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('number_of_likes', models.IntegerField(default=0, null=True, verbose_name='Number Of Likes')),
            ],
        ),
        migrations.CreateModel(
            name='AdvSummary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guid', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=38)),
                ('max_fee_per_like', models.IntegerField()),
                ('expire_date', models.DateField()),
                ('advertisement_image', models.ImageField(blank=True, null=True, upload_to=advertisement.models.user_directory_path, verbose_name='Advertisement Image')),
                ('adv_desc', models.CharField(max_length=255, null=True, verbose_name='Advertisement Description')),
                ('adv_min_follower', models.IntegerField(null=True, verbose_name='Advertisement Minimum Follower')),
                ('adv_max_follower', models.IntegerField(null=True, verbose_name='Advertisement Maximum Follower')),
                ('is_approved', models.BooleanField(default=0)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'advertisement_summary',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('insert_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='advsummary',
            name='categories',
            field=models.ManyToManyField(to='advertisement.Category'),
        ),
        migrations.AddField(
            model_name='advsummary',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertisements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advstats',
            name='adv_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adv_stats', to='advertisement.AdvSummary'),
        ),
        migrations.AddField(
            model_name='advstats',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adv_stats', to=settings.AUTH_USER_MODEL),
        ),
    ]
