# Generated by Django 2.0.5 on 2018-07-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advsummary',
            name='slug_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
