# Generated by Django 2.0.3 on 2018-06-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advsummary',
            name='adv_image',
            field=models.ImageField(blank=True, null=True, upload_to='advertisement_image/%Y/%m/%d',
                                    verbose_name='Advertisement Image'),
        ),
    ]
