# Generated by Django 2.0.3 on 2018-06-12 16:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('advertisement', '0002_auto_20180611_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advsummary',
            old_name='adv_image',
            new_name='advertisement_image',
        ),
    ]
