# Generated by Django 2.0.5 on 2018-06-24 20:57

import advertisement.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_auto_20180612_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advsummary',
            name='adv_slug_name',
        ),
        migrations.RemoveField(
            model_name='advsummary',
            name='brand_slug_name',
        ),
        migrations.AddField(
            model_name='brand',
            name='adv_slug_name',
            field=models.SlugField(allow_unicode=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='advsummary',
            name='advertisement_image',
            field=models.ImageField(blank=True, null=True, upload_to=advertisement.models.user_directory_path, verbose_name='Advertisement Image'),
        ),
        migrations.AlterField(
            model_name='advsummary',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertisements', to=settings.AUTH_USER_MODEL),
        ),
    ]
